version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - fullnet
    depends_on: 
      - app

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    networks:
      - fullnet
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullnet

networks:
  fullnet:
    driver: bridge
